--- #YAML:1.0
name:                Catalyst-Model-SWISH
version:             0.03
abstract:            Catalyst model for Swish-e
license:             ~
author:              
    - Peter Karman <perl@peknet.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst:                      5.7
    Data::Pageset:                 1.03
    NEXT:                          0.6
    Sort::SQL:                     0.01
    SWISH::API::Object:            0.09
    Time::HiRes:                   1.86
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
